# This file is part of kookas/security-checker.
# 
# (c) Ashleigh Udoh <mail@audoh.co.uk>
# 
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    kookas.security_checker:
        class: Kookas\SecurityCheckerBundle\Service\SecurityCheckerService
        arguments: ['@security.authorization_checker', '@security.token_storage',
                    '@security.role_hierarchy', '@security.authentication.trust_resolver',
                    '@router', '@request_stack', '@sensio_framework_extra.security.expression_language']

    kookas.security_checker.twig_extension:
        class: Kookas\SecurityCheckerBundle\Twig\SecurityChecker
        arguments: ["@kookas.security_checker"]
        public: false
        tags:
            - { name: twig.extension }